modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/cazsius/dye-it-yourself/issues"
license="GPL-3.0"
[[mods]] #mandatory
    modId="dyeityourself"
    version="${file.jarVersion}"
    displayName="Dye It Yourself"
    updateJSONURL="http://raw.githubusercontent.com/Cazsius/Dye-It-Yourself/master/update.json"
    displayURL="https:curseforge.com/minecraft/mc-mods/dye-it-yourself"
    #logoFile="logo.png"
    credits=""
    authors="Poke1650, Cazsius, Willbl3pic, Tfarcenim"
    description='''
Lets the sheep dye themselves.
'''

[[dependencies.dyeityourself]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dyeityourself]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"